version: 2

models:
  - name: transactions
    columns:
      - name: account_no
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: date
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
      - name: transaction_details
        tests:
          - not_null
      - name: chq_no
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: value_date
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
      - name: withdrawal_amt
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: deposit_amt
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
      - name: balance_amt
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
          - not_null