version: 2

models:
  - name: transactions
    columns:
      - name: account_no
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: transaction_details
        tests:
          - not_null
      - name: chq_no
        tests:
          - not_null
      - name: value_date
        tests:
          - not_null
      - name: balance_amt
        tests:
          - not_null
      
